### ISSUE TITLE
Delete Bucket Privileges if Just Restoring?

### ISSUE THREAD

**Issue by HenleyChiu** [elastic/elasticsearch-cloud-aws#261]
Do you need delete privileges on the AWS bucket files if the Elastic server is just restoring? (not snapshotting)

**Comment by dadoonet** [comment]
You need delete privileges when you create the repository because elasticsearch will check that it can write a file to the repo and then will remove it.

From elasticsearch 2.1.0, a `readonly` parameter is supported. So I think you can create a S3 repository with `readonly` parameter and in that case you won't need the delete privilege.

If it does not work for you, please open a thread on discuss.elastic.co or open an issue at https://github.com/elastic/elasticsearch/issues
